#!/bin/bash
# Auto-generated by install.sh. Activates the repo-owned venv, sets PYTHONPATH,
# runs the RPi kernel-compatibility check, and loads /usr/local/hailo/resources/.env.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$SCRIPT_DIR/venv"

# RPi kernel-version check (mirrors hailo-apps/setup_env.sh)
if uname -a | grep -q "Linux raspberrypi"; then
    INVALID_KERNELS=("6.12.21" "6.12.22" "6.12.23" "6.12.24" "6.12.25")
    CURRENT_VERSION=$(uname -r | cut -d '+' -f 1)
    for k in "${INVALID_KERNELS[@]}"; do
        if [ "$k" = "$CURRENT_VERSION" ]; then
            echo "Error: Kernel $CURRENT_VERSION is incompatible." >&2
            echo "See https://community.hailo.ai/t/raspberry-pi-kernel-compatibility-issue-temporary-fix/15322" >&2
            return 1
        fi
    done
fi

export PYTHONPATH="$SCRIPT_DIR:$PYTHONPATH"

if [ -d "$VENV_DIR" ]; then
    # shellcheck disable=SC1091
    source "$VENV_DIR/bin/activate"
    echo "Activated venv at $VENV_DIR"
else
    echo "Error: venv not found at $VENV_DIR. Run ./install.sh first." >&2
    return 1
fi

ENV_FILE="/usr/local/hailo/resources/.env"
if [ -f "$ENV_FILE" ]; then
    while IFS='=' read -r key value; do
        [[ -z "$key" || "$key" =~ ^# ]] && continue
        export "$key=$value"
        upper_key=$(echo "$key" | tr '[:lower:]' '[:upper:]')
        export "$upper_key=$value"
    done < "$ENV_FILE"
fi
