name: hotdog_not_hotdog
title: Hotdog Not Hotdog
description: Zero-shot classification using CLIP to determine whether objects are hotdogs.
type: pipeline
entry_point: hotdog_not_hotdog.py
models:
  - clip_image_encoder
hailo_arch:
  - hailo8
  - hailo8l
  - hailo10h
